name: flutter_sandbox
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.4
  freezed_annotation: ^2.4.1
  riverpod_annotation:
  roggle: ^0.4.2+1
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.14

dev_dependencies:
  build_runner:
  custom_lint:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  pedantic_mono: ^1.24.0+1
  riverpod_generator: ^2.3.2
  riverpod_lint: ^2.1.0

flutter:
  uses-material-design: true
