name: flutter_sandbox
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  freezed_annotation: ^2.0.3
  roggle: ^0.2.1
  url_launcher: ^6.1.2

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  pedantic_mono: ^1.18.0

flutter:
  uses-material-design: true
